name:
on:
  push:
    branches: [ "main" ]
env:
  app_version: 1.11.86-sc.0.test.0
permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=${{ env.app_version }},enable=${{ github.ref_name == 'main' }}
      - name: Checkout SchildiChat
        run: |
          wget https://github.com/SchildiChat/schildichat-desktop/releases/download/v${{ env.app_version }}/schildichat-web-alpha-${{ env.app_version }}.tar.gz
          tar -xf schildichat-web-alpha-${{ env.app_version }}.tar.gz
          mv element-${{ env.app_version }} schildichat-web
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}